/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package openingScreen;

import Objects.Category;
import Objects.Product;
import Objects.Sizes;
import database.DatabaseManager;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Jealian Abby Sulit
 */
public class opening extends javax.swing.JFrame {

    public static ArrayList<Product> products = new ArrayList();
    public static ArrayList<Category> categories = new ArrayList();
    public static ArrayList<Sizes> sizes = new ArrayList();

    ImageIcon[] images = new ImageIcon[3];
    int currentImageIndex = 0;
    float[] fontSizes = new float[2];
  
    PreparedStatement ps;
    Statement stmt;
    ResultSet rs;
    String query;
    Product info;
    public static DatabaseManager dbManager = new DatabaseManager();
    Connection conn;
    
    public opening() {
        
         // Database Connections and Objects
        conn = dbManager.connectDatabase();
        
        initComponents();
        displayOpeningScreen();
        displayLabel();
        openScrImages();

        Image icon = Toolkit.getDefaultToolkit().getImage("src/Images/logo.png");
        this.setIconImage(icon);
    }

    private void openScrImages() {
        images[0] = getResizedIcon("/Images/jb1.png", bgLbl.getWidth(), bgLbl.getHeight());
        images[1] = getResizedIcon("/Images/jb2.png", bgLbl.getWidth(), bgLbl.getHeight());
        images[2] = getResizedIcon("/Images/jb3.png", bgLbl.getWidth(), bgLbl.getHeight());

    }

    public ImageIcon getResizedIcon(String path, int width, int height) {

        ImageIcon imageIcon = new ImageIcon(getClass().getResource(path));
        Image img = imageIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon imgIcon = new ImageIcon(img);

        return imgIcon;
    }

    private void displayOpeningScreen() {
        new Thread(() -> {
            try {
                while (true) {
                    bgLbl.setIcon(images[currentImageIndex]);
                    Thread.sleep(2000); // Show image for 2 seconds
                    currentImageIndex = (currentImageIndex + 1) % images.length;
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }

    private void displayLabel() {
        fontSizes[0] = 24f;
        fontSizes[1] = 26f;
        new Thread(() -> {
            try {
                for (int x = 0; x < 1; x--) {
                    for (int i = 0; i < fontSizes.length; i++) { // Increase font size
                        clickLbl.setFont(clickLbl.getFont().deriveFont(fontSizes[i]));
                        Thread.sleep(500); // Pause for smooth animation
                    }
                    for (int i = fontSizes.length - 2; i >= 0; i--) { // Decrease font size
                        clickLbl.setFont(clickLbl.getFont().deriveFont(fontSizes[i]));
                        Thread.sleep(500);
                    }
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        clickLbl = new javax.swing.JLabel();
        bgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Beans");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clickLbl.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        clickLbl.setText("CLICK TO START");
        jPanel2.add(clickLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 340, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 434, 940, 120));

        bgLbl.setText("jLabel2");
        jPanel1.add(bgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 930, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opening().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLbl;
    private javax.swing.JLabel clickLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
