/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Objects;

import admin.Admin_Dashboard;
import java.awt.Color;
import static openingScreen.opening.dbManager;

/**
 *
 * @author Jealian Abby Sulit
 */
public class Category extends javax.swing.JPanel {

    int categoryId;
    String categoryName;
    Color wheat = new Color(245, 222, 179);
    Color rod = new Color(204, 153, 0);

    public Category(int categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        initComponents();
        initCategory();
    }

    public int getCategoryId() {
        return categoryId;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public Category() {
        initComponents();
        initCategory();
    }

    public void initCategory() {
        catLbl.setText(getCategoryName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 153, 0));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(163, 35));
        setMinimumSize(new java.awt.Dimension(163, 35));
        setPreferredSize(new java.awt.Dimension(163, 35));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        catLbl.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        catLbl.setForeground(new java.awt.Color(51, 51, 0));
        catLbl.setText("Category");
        add(catLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(wheat);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(rod);
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        String cat = catLbl.getText().trim();
        if(cat.equals("All")){
            dbManager.retrieveAllProducts(Admin_Dashboard.panelMenu);
        }else{
            dbManager.retrieveProductperCat(cat, Admin_Dashboard.panelMenu);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catLbl;
    // End of variables declaration//GEN-END:variables
}
