/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Objects;

import database.DatabaseManager;
import java.awt.Color;
import java.sql.Connection;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jealian Abby Sulit
 */
public class Product extends javax.swing.JPanel {

    int productId;
    String productName;
    String productSize;
    double price;
    int categoryId;
    byte [] productImage;
    PreparedStatement pstmt;
    Statement stmt;
    Connection conn;
    DatabaseManager db;
    DecimalFormat two = new DecimalFormat("0.00");
    Color wheat = new Color(245, 222, 179);
     Color d= new Color(190,156,106);
     Color rod = new Color(151, 115, 22);
     
    public Product(int productId, String productName,  double price, int categoryId, byte [] productImage) {
        initComponents();
        
        //conn = db.connectDatabase();
        this.productId = productId;
        this.productName = productName;
        this.price = price;
        this.categoryId = categoryId;
        this.productImage = productImage;
        initProducts();
    }

    public Product() {
        initComponents();
        initProducts();
    }

    public int getProductId() {
        return productId;
    }

    public String getProductSize() {
        return productSize;
    }

    public String getProductName() {
        return productName;
    }

    public double getProductPrice() {
        return price;
    }

    public byte [] getProductImage() {
        return productImage;
    }

    public int getProductCategory() {
        return categoryId;
    }

    public void setProductId(int id) {
        this.productId = id;
    }

    public void setProductName(String name) {
        this.productName = name;
    }

    public void setProductSize(String size) {
        this.productSize = size;
    }

    public void setProductPrice(double price) {
        this.price = price;
    }

    public void setProductCategory(int cat) {
        this.categoryId = cat;
    }

    public void setProductImg(byte [] img) {
        this.productImage = img;
    }
    
    
    public void addProduct(int productId, String productName, String productSize, double price, int categoryId,byte [] imgpath) throws FileNotFoundException{
        //File imgFile = new File(imgpath);
        //FileInputStream fis = new FileInputStream (imgFile);
        String query = "INSERT INTO Product (ProductId, ProductName, sizeId, Price, CategoryId, ProductImage) VALUES (?, ?, ?, ?, ?,?)";
        try{
            pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, productId);
            pstmt.setString(2, productName);
            pstmt.setString(3, productSize);
            pstmt.setDouble(4, price);
            pstmt.setInt(5, categoryId);
            pstmt.setBytes(6, imgpath);
            int rowsAffected = pstmt.executeUpdate();
            if(rowsAffected == 1){
                JOptionPane.showMessageDialog(null, "New product was added successfully!", "Success!", JOptionPane.PLAIN_MESSAGE);
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }

    
    public void initProducts() {
        productNameLbl.setText(getProductName());
        productPriceLbl.setText(two.format(getProductPrice()));
        productImgLbl.setIcon(displayImage(getProductImage()));
    }
    

    public ImageIcon displayImage(byte[] imgData) {
        ImageIcon icon = new ImageIcon(imgData);
        Image img = icon.getImage();
        Image img2 = img.getScaledInstance(140, 140, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img2);
        return icon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailsPnl = new javax.swing.JPanel();
        productNameLbl = new javax.swing.JLabel();
        productPriceLbl = new javax.swing.JLabel();
        productImgLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(190, 156, 106));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(200, 240));
        setPreferredSize(new java.awt.Dimension(200, 240));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailsPnl.setBackground(new java.awt.Color(151, 115, 22));
        detailsPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        detailsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productNameLbl.setBackground(new java.awt.Color(51, 51, 0));
        productNameLbl.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        productNameLbl.setText("Name");
        detailsPnl.add(productNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 180, 30));

        productPriceLbl.setBackground(new java.awt.Color(51, 51, 0));
        productPriceLbl.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        productPriceLbl.setText("price");
        detailsPnl.add(productPriceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 40, 150, -1));

        add(detailsPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 70));

        productImgLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(productImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(wheat);
        detailsPnl.setBackground(Color.WHITE);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(d);
        detailsPnl.setBackground(rod);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detailsPnl;
    private javax.swing.JLabel productImgLbl;
    private javax.swing.JLabel productNameLbl;
    private javax.swing.JLabel productPriceLbl;
    // End of variables declaration//GEN-END:variables
}
