/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Users;

import admin.Admin_Dashboard;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static openingScreen.opening.dbManager;
import staff.Staff_Dashboard;

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    Connection conn;
    Map<String, Integer> loginAttempts = new HashMap<>();

    public login() {
        initComponents();

        conn = dbManager.connectDatabase();
        Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Jealian Abby Sulit\\Documents\\NetBeansProjects\\JavaBeans_POS\\src\\Images\\logo.png");
        this.setIconImage(icon);

        //for banner
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\Jealian Abby Sulit\\Documents\\NetBeansProjects\\JavaBeans_POS\\src\\Images\\bglogin.png");
        Image img = imageIcon.getImage();
        Image img2 = img.getScaledInstance(bgLbl.getWidth(), bgLbl.getHeight(), Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(img2);
        bgLbl.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        passTxtF = new javax.swing.JPasswordField();
        userTxtF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Beans: Login");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERNAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 110, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, -1));

        loginBtn.setBackground(new java.awt.Color(153, 102, 0));
        loginBtn.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 180, 50));

        passTxtF.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        passTxtF.setForeground(new java.awt.Color(153, 153, 153));
        passTxtF.setText("Password");
        passTxtF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTxtFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTxtFFocusLost(evt);
            }
        });
        jPanel1.add(passTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 320, 40));

        userTxtF.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        userTxtF.setForeground(new java.awt.Color(153, 153, 153));
        userTxtF.setText("Username");
        userTxtF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userTxtFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTxtFFocusLost(evt);
            }
        });
        jPanel1.add(userTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 320, 40));

        jLabel1.setFont(new java.awt.Font("STKaiti", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
        jPanel1.add(bgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:

        String username = userTxtF.getText().trim();
        String password = new String(passTxtF.getPassword()).trim();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both username and password.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

// Admin login
        if (username.equals("Admin") && password.equals("Admin123")) {
            this.setVisible(false);
            Admin_Dashboard dashB = new Admin_Dashboard();
            dashB.setVisible(true);
            return;
        }else{
            JOptionPane.showMessageDialog(null, "error", "Invalid username or password",JOptionPane.ERROR_MESSAGE );
        }
        if(username.equals("Admin")){
            return;
        }

// First, check if account is already blocked in DB
        try {
            PreparedStatement checkStatus = conn.prepareStatement("SELECT Status FROM userInfo WHERE UserId = ?");
            checkStatus.setString(1, username);
            ResultSet statusResult = checkStatus.executeQuery();

            if (statusResult.next()) {
                String status = statusResult.getString("Status");
                if ("Blocked".equalsIgnoreCase(status)) {
                    JOptionPane.showMessageDialog(this, "Your account is BLOCKED. Please contact the admin.", "Blocked", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (SQLException e) {
            return;
        }

// Login attempt check
        try {
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM userInfo WHERE UserId = ? AND emailAdd = ?");
            ps.setString(1, username);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // Successful login
                loginAttempts.remove(username); // reset attempt
                this.setVisible(false);
                Staff_Dashboard userDash = new Staff_Dashboard();
                userDash.setVisible(true);
            } else {
                // Invalid login
                int attempts = loginAttempts.getOrDefault(username, 0) + 1;
                loginAttempts.put(username, attempts);

                if (attempts >= 5) {
                    // Block the account in DB
                    PreparedStatement blockStmt = conn.prepareStatement("UPDATE userInfo SET Status = 'Blocked' WHERE UserId = ?");
                    blockStmt.setString(1, username);
                    blockStmt.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Too many failed attempts. Your account has been BLOCKED.", "Blocked", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect credentials. Attempt " + attempts + " of 5.", "Login Failed", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (SQLException e) {

        }


    }//GEN-LAST:event_loginBtnActionPerformed

    private void userTxtFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTxtFFocusGained
        if (String.valueOf(userTxtF.getText()).equals("Username")) {
            userTxtF.setText("");
            userTxtF.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_userTxtFFocusGained

    private void userTxtFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTxtFFocusLost
        if (String.valueOf(userTxtF.getText()).isEmpty()) {
            userTxtF.setText("Username");
            userTxtF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_userTxtFFocusLost

    private void passTxtFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTxtFFocusGained
        if (String.valueOf(passTxtF.getText()).equals("Password")) {
            passTxtF.setText("");
            passTxtF.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_passTxtFFocusGained

    private void passTxtFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTxtFFocusLost
        if (String.valueOf(passTxtF.getText()).isEmpty()) {
            passTxtF.setText("Password");
            passTxtF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_passTxtFFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.requestFocusInWindow(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passTxtF;
    private javax.swing.JTextField userTxtF;
    // End of variables declaration//GEN-END:variables
}
