/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package staff;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;
import static openingScreen.opening.dbManager;

/**
 *
 * @author Jealian Abby Sulit
 */
public class Staff_Dashboard extends javax.swing.JFrame {
//COLORS

    Color wheat = new Color(245, 222, 179);
    Color wood = new Color(190, 156, 106);

    // Database
    Connection conn;

    public Staff_Dashboard() {
        initComponents();
        // Database Connections and Objects
        conn = dbManager.connectDatabase();

    //for banner
    ImageIcon imageIcon = new ImageIcon("C:\\Users\\Jealian Abby Sulit\\Documents\\NetBeansProjects\\JavaBeans_POS\\src\\Images\\header.png");
    Image img = imageIcon.getImage();
    Image img2 = img.getScaledInstance(headerLbl.getWidth(), headerLbl.getHeight(), Image.SCALE_SMOOTH);
    imageIcon = new ImageIcon(img2);
    headerLbl.setIcon(imageIcon);
        
        displayProducts();
        displayCategories();

    }

    public void displayProducts() {
        dbManager.retrieveAllProducts(panelMenu);
    }

    public void displayCategories() {
        dbManager.retrieveAllCategories(categoryPnl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ordersBdy = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        subTValue = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        orderId = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        totalValue = new javax.swing.JLabel();
        taxValue = new javax.swing.JLabel();
        clearOrdersBtn = new javax.swing.JButton();
        orderScroll = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        bannerPnl = new javax.swing.JPanel();
        searchF = new javax.swing.JTextField();
        headerTitle = new javax.swing.JLabel();
        headerLbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        scrollPane1 = new javax.swing.JScrollPane();
        panelMenu = new javax.swing.JPanel();
        categoryScrll = new javax.swing.JScrollPane();
        categoryPnl = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1310, 820));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ordersBdy.setBackground(new java.awt.Color(204, 153, 0));
        ordersBdy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ORDER ID #");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 50));

        jLabel8.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SUBTOTAL: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 30));

        subTValue.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        subTValue.setForeground(new java.awt.Color(255, 255, 255));
        subTValue.setText("0");
        jPanel2.add(subTValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 30));

        jLabel23.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("PHP");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 60, 30));

        orderId.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        orderId.setForeground(new java.awt.Color(255, 255, 255));
        orderId.setText("0000");
        jPanel2.add(orderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, 30));

        ordersBdy.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 90));

        jPanel3.setBackground(new java.awt.Color(153, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TOTAL: ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setText("PLACE ORDER");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 170, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TAX:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, 30));

        totalValue.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        totalValue.setForeground(new java.awt.Color(255, 255, 255));
        totalValue.setText("0");
        jPanel3.add(totalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 170, 30));

        taxValue.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        taxValue.setForeground(new java.awt.Color(255, 255, 255));
        taxValue.setText("0");
        jPanel3.add(taxValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 170, 30));

        clearOrdersBtn.setBackground(new java.awt.Color(204, 204, 204));
        clearOrdersBtn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        clearOrdersBtn.setText("RESET");
        clearOrdersBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(clearOrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 40));

        ordersBdy.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 420, 150));

        orderScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(204, 153, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        orderScroll.setViewportView(jPanel4);

        ordersBdy.add(orderScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 420, 430));

        jPanel1.add(ordersBdy, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 420, 670));

        bannerPnl.setBackground(new java.awt.Color(104, 70, 3));
        bannerPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchF.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        searchF.setForeground(new java.awt.Color(102, 102, 102));
        searchF.setText("Search Product/Category");
        searchF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFFocusLost(evt);
            }
        });
        bannerPnl.add(searchF, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 420, 40));

        headerTitle.setFont(new java.awt.Font("STLiti", 1, 48)); // NOI18N
        headerTitle.setForeground(new java.awt.Color(255, 255, 255));
        headerTitle.setText("Java Beans Point of Sales System");
        bannerPnl.add(headerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 620, 90));
        bannerPnl.add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 90));

        jPanel1.add(bannerPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 90));

        jPanel5.setBackground(new java.awt.Color(229, 207, 175));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 0), 1, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort By", "Id", "Name", "Price" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 270, 40));

        scrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        scrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelMenu.setBackground(new java.awt.Color(83, 71, 0));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu.setLayout(new java.awt.GridLayout(0, 3, 30, 20));
        scrollPane1.setViewportView(panelMenu);

        jPanel5.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 700, 500));

        categoryScrll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        categoryPnl.setBackground(new java.awt.Color(153, 102, 0));
        categoryPnl.setBorder(new javax.swing.border.MatteBorder(null));
        categoryScrll.setViewportView(categoryPnl);

        jPanel5.add(categoryScrll, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 700, 70));

        jLabel15.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        jLabel15.setText("JAVA BEANS MENU");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 360, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 840, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 820));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFFocusGained
        if (String.valueOf(searchF.getText()).equals("Search Product/Category")) {
            searchF.setText("");
            searchF.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchFFocusGained

    private void searchFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFFocusLost
        if (String.valueOf(searchF.getText()).isEmpty()) {
            searchF.setText("Search Product/Category");
            searchF.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_searchFFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bannerPnl;
    private javax.swing.JPanel categoryPnl;
    private javax.swing.JScrollPane categoryScrll;
    private javax.swing.JButton clearOrdersBtn;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel orderId;
    private javax.swing.JScrollPane orderScroll;
    private javax.swing.JPanel ordersBdy;
    public static javax.swing.JPanel panelMenu;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JTextField searchF;
    private javax.swing.JLabel subTValue;
    private javax.swing.JLabel taxValue;
    private javax.swing.JLabel totalValue;
    // End of variables declaration//GEN-END:variables
}
