/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import Objects.Category;
import Objects.Product;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import static openingScreen.opening.dbManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Jealian Abby Sulit
 */
public class modifyCategory extends javax.swing.JFrame {

    Connection conn;
    //COLORS
    Color wheat = new Color(245, 222, 179);
    Color wood = new Color(190, 156, 106);
    
     PreparedStatement pstmt;
    Statement stmt;
    ResultSet rs;
    Product details;
    Category cat;
    ResultSetMetaData rsmd;
    int colCount;
    Admin_Dashboard d;
    String query;
    Category c;

    public modifyCategory() {
        initComponents();

        Image icon = Toolkit.getDefaultToolkit().getImage("src/Images/logo.png");
        this.setIconImage(icon);

        // Database Connections and Objects
        conn = dbManager.connectDatabase();

        //for banner
        ImageIcon imageIcon = new ImageIcon("C:\\Users\\Jealian Abby Sulit\\Documents\\NetBeansProjects\\JavaBeans_POS\\src\\Images\\header.png");
        Image img = imageIcon.getImage();
        Image img2 = img.getScaledInstance(headerLbl.getWidth(), headerLbl.getHeight(), Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(img2);
        headerLbl.setIcon(imageIcon);

        JTableHeader header = catTbl.getTableHeader();
        header.setFont(new Font("Serif", Font.BOLD, 13));
        header.setBackground(wood); // Coffee brown
        header.setForeground(Color.BLACK);
        ((DefaultTableCellRenderer) header.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
        dbManager.retrieveAllCategories(catTbl);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bannerPnl = new javax.swing.JPanel();
        headerTitle = new javax.swing.JLabel();
        headerLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        catIdTxtF = new javax.swing.JTextField();
        catNameTxtF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        clrBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Category");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bannerPnl.setBackground(new java.awt.Color(104, 70, 3));
        bannerPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerTitle.setFont(new java.awt.Font("STLiti", 1, 36)); // NOI18N
        headerTitle.setForeground(new java.awt.Color(255, 255, 255));
        headerTitle.setText("Java Beans");
        bannerPnl.add(headerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 300, 80));
        bannerPnl.add(headerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 80));

        jPanel1.add(bannerPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 80));

        catTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Category ID", "Category Name"
            }
        ));
        catTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        catTbl.setShowVerticalLines(true);
        catTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(catTbl);
        if (catTbl.getColumnModel().getColumnCount() > 0) {
            catTbl.getColumnModel().getColumn(0).setResizable(false);
            catTbl.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 330, 490, 120));

        jLabel1.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel1.setText("PRODUCT CATEGORY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 310, 40));

        jLabel2.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jLabel2.setText("Category ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 160, 30));

        jLabel3.setFont(new java.awt.Font("STSong", 1, 18)); // NOI18N
        jLabel3.setText("Category Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, -1));

        catIdTxtF.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        catIdTxtF.setForeground(new java.awt.Color(102, 102, 102));
        catIdTxtF.setText("Auto-Generated");
        catIdTxtF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(catIdTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 250, 40));

        catNameTxtF.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        catNameTxtF.setForeground(new java.awt.Color(102, 102, 102));
        catNameTxtF.setText("Enter Category Name");
        catNameTxtF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(catNameTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 250, 40));

        addBtn.setBackground(new java.awt.Color(0, 102, 51));
        addBtn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("ADD");
        addBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 120, 30));

        updateBtn.setBackground(new java.awt.Color(0, 51, 102));
        updateBtn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("UPDATE");
        updateBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 120, 30));

        deleteBtn.setBackground(new java.awt.Color(102, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("DELETE");
        deleteBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 110, 30));

        clrBtn.setBackground(new java.awt.Color(153, 153, 153));
        clrBtn.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        clrBtn.setForeground(new java.awt.Color(255, 255, 255));
        clrBtn.setText("CLEAR");
        clrBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(clrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void catTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catTblMouseClicked
        try {
            int i = catTbl.getSelectedRow();
            if (i == -1) {
                JOptionPane.showMessageDialog(null, "Please select a category first!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String value = String.valueOf(catTbl.getValueAt(i, 0));
            int id = Integer.parseInt(value);

            stmt = conn.createStatement();
            query = "SELECT * FROM category WHERE CategoryId = '" + id + "'";
            rs = stmt.executeQuery(query);
            
            if(rs.next()){
                int catId = rs.getInt("CategoryId");
                String catName = rs.getString("CategoryName");
                c = new Category(catId, catName);
                catIdTxtF.setText(String.valueOf(c.getCategoryId()));
                catNameTxtF.setText(c.getCategoryName());
            }
        } catch (SQLException ex) {
            Logger.getLogger(modifyCategory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_catTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifyCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifyCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifyCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifyCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifyCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel bannerPnl;
    private javax.swing.JTextField catIdTxtF;
    private javax.swing.JTextField catNameTxtF;
    private javax.swing.JTable catTbl;
    private javax.swing.JButton clrBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
